config/routes.rb
Rails.application.routes.draw do
  get 'tracks/show'
  get 'search/index'
  devise_for :users

  namespace :admin do
    resources :dashboard
    # get "dashboard", to: "dashboard#index", as: "dashboard_index"
    get 'users', to: 'dashboard#users', as: 'users'
    get 'promote_to_admin/:user_id', to: 'dashboard#promote_to_admin', as: 'promote_to_admin'
    get 'revoke_admin/:user_id', to: 'dashboard#revoke_admin', as: 'revoke_admin'
    resources :albums, only: [:destroy, :edit, :update, :new, :create]
    get "albums/destroy/:id", to: "albums#destroy", as: "album_destroy"

    resources :tracks, only: [:destroy, :edit, :update, :new, :create]
    get "tracks/destroy/:id", to: "tracks#destroy", as: "track_destroy"
  end

  # get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"

  get "albums/:id", to: "pages#show", as: "album"
  get 'search', to: 'search#index'
  get 'random_album', to: 'pages#random_album'

  get "tracks/:id", to: "tracks#show", as: "track"
end

app/models/album.rb
class Album < ApplicationRecord
    has_many :tracks, dependent: :destroy
    has_and_belongs_to_many :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :albums
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :album
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/albums_controller.rb
# app/controllers/albums_controller.rb
class Admin::AlbumsController < Admin::BaseController
  # Other actions
  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_path(@album), notice: 'Album was successfully created.'
    else
      render :new
    end
  end

  def destroy
    album = Album.find(params[:id])
    album.destroy
    redirect_to root_path, notice: 'Album was successfully deleted.'
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_path, notice: 'Album was successfully updated.'
    else
      render :edit
    end
  end

  private

  def album_params
    params.require(:album).permit(:name, :author, :release_year, :cover_image, :length, :quantity)
  end
end

app/controllers/admin/base_controller.rb
module Admin
    class BaseController < ApplicationController
        before_action :check_if_admin

        def users
            @users = User.all
        end

        def promote_to_admin
            user = User.find(params[:user_id])
            user.update(admin: true)
            redirect_to admin_users_path, notice: "#{user.email} has been promoted to admin."
        end

        def revoke_admin
            user = User.find(params[:user_id])
            user.update(admin: false)
            redirect_to admin_users_path, notice: "#{user.email} no longer has administrator privileges."
        end

        private

        def check_if_admin
            redirect_to root_path unless current_user.admin?
        end
    end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
    layout "admin/base"

    def index; end
end

app/controllers/admin/tracks_controller.rb
class Admin::TracksController < Admin::BaseController

  def new
    @track = Track.new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to @track, notice: 'Track was successfully created.'
    else
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to @track, notice: 'Track was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    track = Track.find(params[:id])
    track.destroy
    redirect_to root_path, notice: 'Track was successfully deleted.'
  end

  private
    
  def track_params
    params.require(:track).permit(:name, :length, :lyrics, :album_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :authenticate_user!

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) do |user_params|
            user_params.permit(:email, :password, :password_confirmation, :admin)
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # @albums = Album.all
    @sort_column = params[:sort_column] || 'name'
    @sort_direction = params[:sort_direction] || 'asc'
    @albums = Album.order("#{@sort_column} #{@sort_direction}")
  end

  def show
    @album = Album.find(params[:id])
  end

  def random_album
    @album = Album.order("RAND()").first
    redirect_to album_path(@album)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = params[:query]
    @category = params[:category]

    @results = if @category == "Name"
                 Album.where("name LIKE ?", "%#{@query}%") + Track.where("name LIKE ?", "%#{@query}%")
               elsif @category == "Author"
                 Album.where("author LIKE ?", "%#{@query}%") # + Track.where("author LIKE ?", "%#{@query}%")
               elsif @category == "Lyrics"
                 Track.where("lyrics LIKE ?", "%#{@query}%")
               else
                 []
               end
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    

  def show
    @track = Track.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/admin/albums/edit.html.erb
<%= form_with(model: @album, url: admin_album_path(@album), html: {multipart: true}, method: :patch) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>
  <div class="field">
    <%= form.label :release_year %>
    <%= form.number_field :release_year %>
  </div>
  <div class="field">
    <%= form.label :cover_image %>
    <%= form.file_field :cover_image %>
  </div>
  <div class="field">
    <%= form.label :length %>
    <%= form.text_field :length %>
  </div>
  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>
  <%= form.submit %>
<% end %>

app/views/admin/albums/new.html.erb
<%= form_with(model: @album, url: admin_albums_path, method: :post, multipart: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>
  <div class="field">
    <%= form.label :release_year %>
    <%= form.number_field :release_year %>
  </div>
  <div class="field">
    <%= form.label :cover_image %>
    <%= form.file_field :cover_image %>
  </div>
  <div class="field">
    <%= form.label :length %>
    <%= form.text_field :length %>
  </div>
  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/dashboard/index.html.erb
<h1>Hello, Admin! Welcome to admin section! (^_^)</h1>

<%= link_to "Manage Users", admin_users_path %><br>
<%= link_to 'Create New Album', new_admin_album_path %><br>
<%= link_to 'Create New Track', new_admin_track_path %><br>

app/views/admin/dashboard/users.html.erb
<div class="container">
  <h2>All Users</h2>
  <p>Here you can promote accounts to admin and revoke this privileges.</p>            
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Email</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td>
            <% unless user.admin? %>
              <%= link_to "Promote to admin", admin_promote_to_admin_path(user_id: user.id), method: :patch %>
            <% end %>
            <% unless !user.admin? %>
              <%= link_to "Revoke admin", admin_revoke_admin_path(user_id: user.id), method: :patch %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/tracks/edit.html.erb
<%= form_with(model: @track, url: admin_track_path(@track), html: {multipart: true}, method: :patch) do |form| %>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div class="field">
      <%= form.label :length %>
      <%= form.text_field :length %>
    </div>
    <div class="field">
      <%= form.label :lyrics %>
      <%= form.text_area :lyrics %>
    </div>
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/admin/tracks/new.html.erb
<%= form_with(model: @track, url: admin_tracks_path, method: :post, multipart: true) do |form| %>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div class="field">
      <%= form.label :length %>
      <%= form.text_field :length %>
    </div>
    <div class="field">
      <%= form.label :lyrics %>
      <%= form.text_area :lyrics %>
    </div>
    <div class="field">
      <%= form.label :album_id %>
      <%= form.collection_select(:album_id, Album.all, :id, :name, prompt: "Select an album") %>
    </div>
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/layouts/admin/base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoicesOfTheVoid</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>

  <body class="admin">
    <div class="header">
      <%= link_to "VOTV", root_path %>

      <div class="search-form">
        <%= form_tag(search_path, method: "get") do %>
          <%= text_field_tag :query, params[:query], placeholder: "Search..." %>
          <%= select_tag :category, options_for_select(["Name", "Author", "Lyrics"]) %>
          <%= submit_tag "Search" %>
        <% end %>
      </div>

      <div class="user-links">
        <% if user_signed_in? && current_user.admin? %>
          <p>Welcome, <%= link_to "Admin", admin_dashboard_index_path %>!</p>
        <% else %>
          <p>Welcome, User!</p>
        <% end %>

        <% if user_signed_in? %>
          <%= link_to "Edit registration", edit_user_registration_path %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Register", new_user_registration_path %>
          <%= link_to "Login", new_user_session_path %>
        <% end %>
      </div>
    </div>



    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <div class="wrapper">
      <%= yield %>
    </div>
  </body>


  <style>
  .header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 10px 20px;
    background-color: #f8f9fa;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
  }

  .search-form {
    display: flex;
    align-items: center;
    gap: 10px;
  }

  .user-links {
    display: flex;
    gap: 10px;
  }

  @media (max-width: 768px) {
    .header {
      flex-direction: column;
      align-items: stretch;
    }
    
    .search-form {
      margin-top: 10px;
    }
    
    .user-links {
      margin-top: 10px;
    }
  }

  .wrapper {
    margin: 0% 3% 3% 3%;
    padding: 0% 3% 3% 3%;
  }
  </style>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoicesOfTheVoid</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>

  <body>
    <div class="header">
      <%= link_to "VOTV", root_path %>

      <div class="search-form">
        <%= form_tag(search_path, method: "get") do %>
          <%= text_field_tag :query, params[:query], placeholder: "Search..." %>
          <%= select_tag :category, options_for_select(["Name", "Author", "Lyrics"]) %>
          <%= submit_tag "Search" %>
        <% end %>
      </div>

      <div class="user-links">
        <% if user_signed_in? && current_user.admin? %>
          <p>Welcome, <%= link_to "Admin", admin_dashboard_index_path %>!</p>
        <% else %>
          <p>Welcome, User!</p>
        <% end %>

        <% if user_signed_in? %>
          <%= link_to "Edit registration", edit_user_registration_path %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Register", new_user_registration_path %>
          <%= link_to "Login", new_user_session_path %>
        <% end %>
      </div>
    </div>



    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>



    <div class="wrapper">
      <%= yield %>
    </div>
  </body>



  <style>
  .header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 10px 20px;
    background-color: #f8f9fa;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
  }

  .search-form {
    display: flex;
    align-items: center;
    gap: 10px;
  }

  .user-links {
    display: flex;
    gap: 10px;
  }

  @media (max-width: 768px) {
    .header {
      flex-direction: column;
      align-items: stretch;
    }
    
    .search-form {
      margin-top: 10px;
    }
    
    .user-links {
      margin-top: 10px;
    }
  }

  .wrapper {
    margin: 0% 3% 3% 3%;
    padding: 0% 3% 3% 3%;
  }
  </style>
</html>

app/views/pages/home.html.erb
<h1>Welcome to the "Voices of the Void"! :)</h1>
<p>Grab some tea, stay here and listen to some awesome tunes.</p>
<p>Hope, you'll like this collection. (^_^)</p>
<br>
<h2>Albums avialable</h2><br>

<% if user_signed_in? && current_user.admin? %>
<div class="container mt-4">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th><%= link_to "Name", root_path(sort_column: 'name', sort_direction: @sort_column == 'name' && @sort_direction == 'asc' ? 'desc' : 'asc') %></th>
        <th><%= link_to "Author", root_path(sort_column: 'author', sort_direction: @sort_column == 'author' && @sort_direction == 'asc' ? 'desc' : 'asc') %></th>
        <th><%= link_to "Release Year", root_path(sort_column: 'release_year', sort_direction: @sort_column == 'release_year' && @sort_direction == 'asc' ? 'desc' : 'asc') %></th>
        <th>Length</th>
        <th>Quantity</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= link_to album.name, album_path(album) %></td>
        <td><%= album.author %></td>
        <td><%= album.release_year %></td>
        <td><%= album.length %></td>
        <td><%= album.quantity %></td>
        <td>
            <%= link_to "Delete", admin_album_destroy_path(album), method: :delete, data: { confirm: "Are you sure?" } %>
            <%= link_to "Edit", edit_admin_album_path(album) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<% else %>
    <div class="container_css">
        <% @albums.each do |album| %>
            <div class="card">
                <img src="album1.jpg" alt="Album cover">
                <div class="card-body">
                    <h2 class="card-title"><%= link_to album.name, album_path(album) %></h2>
                    <p class="card-text">by <%= album.author %></p>
                </div>
            </div>
        <% end %>
    </div>
<% end %>

<%= button_to "Random Album", random_album_path, method: :get %>

<style>
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
  }
  .container_css {
    max-width: 1200px;
    margin: 20px auto;
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
    grid-gap: 20px;
    padding: 0 20px;
  }
  .card {
    border: 1px solid #ddd;
    border-radius: 8px;
    overflow: hidden;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    transition: transform 0.2s;
  }
  .card:hover {
    transform: translateY(-5px);
  }
  .card img {
    width: 100%;
    height: 200px;
    object-fit: cover;
    border-bottom: 1px solid #ddd;
  }
  .card-body {
    padding: 10px;
  }
  .card-title {
    font-size: 1.2rem;
    margin-bottom: 5px;
  }
  .card-text {
    font-size: 1rem;
    color: #666;
  }
</style>

app/views/pages/show.html.erb
  <h1><%= @album.name %></h1>

  <div class="field">
    Author: <%= @album.author %>
  </div>
  <div class="field">
    Release year: <%= @album.release_year %>
  </div>
  <div class="field">
    Length: <%= @album.length %>
  </div>
  <div class="field">
    Quantity: <%= @album.quantity %>
  </div>

  <% if @album.tracks != [] %>
    <h3>List of tracks:</h3>
    <div class="container mt-4">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Length</th>
            <% if current_user.admin? %>
              <th>Actions</th>
            <% end %>            

          </tr>
        </thead>
        <tbody>
        <% @album.tracks.each do |track| %>
          <tr>
            <td><%= link_to track.name, track_path(track) %></td>
            <td><%= track.length %></td>
            <td>
              <% if current_user.admin? %>
                <%= link_to 'Edit', edit_admin_track_path(track) %>
                <%= link_to "Delete", admin_track_destroy_path(track) %>
              <% end %>            

            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  <% end %>

<style>
  
</style>

app/views/search/index.html.erb
<h1>Search Results</h1>
<% if @results.present? %>
  <ul>
    <% @results.each do |result| %>
      <% if result.is_a?(Album) %>
        <li><%= link_to result.name, album_path(result) %> by <%= result.author %></li>
      <% elsif result.is_a?(Track) %>
        <li><%= link_to "#{result.album.name} - #{result.name}", album_track_path(result.album, result) %></li>
      <% end %>
    <% end %>
  </ul>
<% else %>
  <p>No results found.</p>
<% end %>

app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>
<div class="field">
    Length: <%= @track.length %>
</div>
<div class="field">
    Lyrics: <%= simple_format @track.lyrics %>
</div>